services:
  - type: web
    name: lbpo-studio-v0-5-backend
    env: node
    plan: free
    buildCommand: "npm install"
    startCommand: "npm start"
    envVars:
      - key: NODE_ENV
        value: production
      - key: SUBSCRIPTION_PRICE
        value: 5
